"""new

Revision ID: a7da3dd98296
Revises: 40ded0db18d5
Create Date: 2024-11-21 12:48:14.900562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7da3dd98296'
down_revision = '40ded0db18d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('rented_at')
        batch_op.drop_column('return_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('rented_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('due_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
