"""new

Revision ID: aed48627bddd
Revises: 5a70614764a4
Create Date: 2024-11-22 12:43:24.287893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed48627bddd'
down_revision = '5a70614764a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workouts')
    op.drop_table('goals')
    op.drop_table('members')
    op.drop_table('exercises')
    op.drop_table('member_workout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_workout',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('workout_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name='fk_member_workout_member_id_members'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='fk_member_workout_workout_id_workouts'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workout_id', sa.INTEGER(), nullable=False),
    sa.Column('sets', sa.INTEGER(), nullable=True),
    sa.Column('reps', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('duration', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='fk_exercises_workout_id_workouts'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('height', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('goals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('goal_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('target_value', sa.FLOAT(), nullable=True),
    sa.Column('current_value', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name='fk_goals_member_id_members'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
